# Generated by Django 5.0.3 on 2024-03-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
    ]
