# Generated by Django 5.0.3 on 2024-03-08 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('age',
                 models.PositiveIntegerField()
                 ),
                ('user',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     primary_key=True,
                     serialize=False,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
