# Generated by Django 5.0.3 on 2024-03-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('password',
                 models.CharField
                 (max_length=128,
                  verbose_name='password')),
                ('last_login',
                 models.DateTimeField(
                     blank=True,
                     null=True,
                     verbose_name='last login')),
                ('email',
                 models.EmailField(
                     error_messages=
                     {'unique': 'A user with that email already exists.'},
                     max_length=254,
                     unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('age', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
