# Generated by Django 5.0.1 on 2024-02-10 14:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(blank=True, max_length=24, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.category'),
        ),
    ]
