# Generated by Django 5.0.1 on 2024-02-01 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name',
                 models.CharField(max_length=32,
                                  validators=[django.core.validators.MinLengthValidator(15)])),
            ],
        ),
    ]
