# Generated by Django 5.0.2 on 2024-02-24 07:32

import django.core.validators
import djangoProject.profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinValueValidator(3, message='Username must be at least 3 chars long!'), djangoProject.profile.validators.validate_username])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(21, message='Age requirement: 21 years and above.')])),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_pic', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
