# Generated by Django 5.0.2 on 2024-02-24 10:39

import django.core.validators
import djangoProject.profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3, message='Username must be at least 3 chars long!'), djangoProject.profile.validators.validate_username]),
        ),
    ]
