# Generated by Django 5.0.2 on 2024-02-24 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1, message='Model must be at least 1 character long.')]),
        ),
    ]
