# Generated by Django 5.0.2 on 2024-02-24 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(help_text='Age requirement: 21 years and above.', validators=[django.core.validators.MinValueValidator(21, message='Age requirement: 21 years and above.')]),
        ),
    ]
