# Generated by Django 5.0.1 on 2024-01-23 18:27

import forms_basic.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[forms_basic.web.models.non_empty_spaces])),
                ('last_name', models.CharField(max_length=50)),
                ('roles', models.IntegerField(choices=[(1, 'software developer'), (2, 'web developer')])),
            ],
        ),
    ]
