# Generated by Django 3.2.7 on 2023-12-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='number',
        ),
    ]
