# Generated by Django 5.0.2 on 2024-02-20 20:23

import django.core.validators
import django.db.models.deletion
import django.views.generic.edit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_genre_alter_album_image_alter_album_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditAlbumView',
            fields=[
                ('album_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='albums.album')),
            ],
            bases=('albums.album', django.views.generic.edit.UpdateView),
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
