# Generated by Django 5.0.1 on 2024-02-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_person_age_person_last_name_alter_person_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='web/profile_images'),
        ),
    ]
