# Generated by Django 5.0.2 on 2024-02-19 17:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Pop Music', 'POP'), ('Jazz Music', 'JAZZ'), ('R&B Music', 'RNB'), ('Rock Music', 'ROCK'), ('Country Music', 'COUNTRY'), ('Dance Music', 'DANCE'), ('Hip Hop Music', 'HIPHOP'), ('Other', 'OTHER')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.profile')),
            ],
        ),
    ]
